-- GENERATED BY scripts/build_verification.sh. DO NOT EDIT.
-- Source: Verification/Headlines.lean

import Verification.Definitions

-- Phase-3 status: hand-written crown-jewel statements pending activation of Tier 3
-- comparator. Until then, each headline is tracked as a named comment. The
-- extractor regenerates this file deterministically so that CI diff-checks pass.

-- TODO(tier-3): challenge statement for MeasureTheory.AnalyticSet.nullMeasurableSet
-- TODO(tier-3): challenge statement for MeasureTheory.AnalyticSet.compactCap_eq
-- TODO(tier-3): challenge statement for MeasureTheory.AnalyticSet.cap_eq_iSup_isCompact
-- TODO(tier-3): challenge statement for ProbabilityTheory.chebyshev_majority_bound
-- TODO(tier-3): challenge statement for BinaryMatrix.assouad_transpose_vcDim
-- TODO(tier-3): challenge statement for ProbabilityTheory.covering_minimax
-- TODO(tier-3): challenge statement for ProbabilityTheory.finite_approx_minimax
-- TODO(tier-3): challenge statement for ProbabilityTheory.mwu_potential_T_bound
-- TODO(tier-3): challenge statement for ProbabilityTheory.mwu_approx_minimax
