/-
Copyright (c) 2026 Dhruv Gupta. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dhruv Gupta
-/

import Lean
import Verification.Definitions
import Verification.Headlines

/-!
# Verification.Extract

Lean executable that regenerates three artifacts from
`Verification.Headlines.headlines`:

- `Verification/ChallengeCrown.lean`: one `theorem challenge_<n> : <type> := sorry` per headline
- `Verification/SolutionCrown.lean`: one `theorem challenge_<n> : <type> := <n>` per headline
- `premise/final.json`: JSON array of `{ "name", "type" }` pairs

Invoked by `scripts/build_verification.sh` in three modes (`challenge`,
`solution`, `premise`). CI regenerates and `git diff --exit-code`s the
three files to catch drift.

Phase 0 operates on an empty headline list, so all three modes emit
boilerplate-only output. Phase 1 extends this by resolving each name
against the imported environment to fetch its type.
-/

open Lean

namespace Verification.Extract

def headerChallenge : String :=
"-- GENERATED BY scripts/build_verification.sh. DO NOT EDIT.
-- Source: Verification/Headlines.lean

import Verification.Definitions

"

def headerSolution : String :=
"-- GENERATED BY scripts/build_verification.sh. DO NOT EDIT.
-- Source: Verification/Headlines.lean

import Verification.Definitions
import ZPM

"

def emitChallenge (hs : List Name) : IO Unit := do
  IO.print headerChallenge
  if hs.isEmpty then
    IO.println "-- No headline theorems declared yet."
  else
    -- Phase 1: per-headline emission resolving each name against the environment.
    for n in hs do
      IO.println s!"-- TODO(phase-1): challenge for {n}"

def emitSolution (hs : List Name) : IO Unit := do
  IO.print headerSolution
  if hs.isEmpty then
    IO.println "-- No headline theorems declared yet."
  else
    for n in hs do
      IO.println s!"-- TODO(phase-1): solution for {n}"

def emitPremise (hs : List Name) : IO Unit := do
  IO.println "{"
  if hs.isEmpty then
    IO.println "  \"theorems\": []"
  else
    IO.println "  \"theorems\": ["
    let total := hs.length
    let mut idx : Nat := 0
    for n in hs do
      let sep := if idx + 1 < total then "," else ""
      IO.println s!"    \{ \"name\": \"{n}\" }{sep}"
      idx := idx + 1
    IO.println "  ]"
  IO.println "}"

end Verification.Extract

open Verification.Extract Verification.Headlines

def main (args : List String) : IO Unit := do
  let mode := args.head?.getD ""
  match mode with
  | "challenge" => emitChallenge headlines
  | "solution"  => emitSolution  headlines
  | "premise"   => emitPremise   headlines
  | _ => do
      IO.eprintln "usage: verification_extract {challenge|solution|premise}"
      IO.Process.exit 1
