/-
Copyright (c) 2026 Dhruv Gupta. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dhruv Gupta
-/

import Lean
import Verification.Definitions
import Verification.Headlines

/-!
# Verification.Extract

Lean executable that regenerates three artifacts from
`Verification.Headlines.headlines`:

- `Verification/ChallengeCrown.lean`: placeholder stubs for each headline.
  When the Tier 3 comparator is activated, these stubs are hand-replaced
  with the full theorem statements plus `sorry`. The comparator then
  checks that the hand-written Challenge statements match the Solution
  statements by shape.
- `Verification/SolutionCrown.lean`: one `theorem challenge_<flatName> := @<n>`
  re-export per headline. Lean's type elaboration copies the original
  theorem's type over; no pretty-printer round-trip needed.
- `premise/final.json`: JSON inventory of `{ name, type }` pairs for every
  headline (name is fully qualified, type is a pretty-printed informational
  string).

Invoked by `scripts/build_verification.sh` in three modes (`challenge`,
`solution`, `premise`). CI regenerates and `git diff --exit-code`s the
three files to catch drift.
-/

open Lean

namespace Verification.Extract

/-- Replace dots with underscores so a fully-qualified name becomes a valid
unqualified Lean identifier. -/
def flatName (n : Name) : String :=
  n.toString.replace "." "_"

/-- Escape a string for JSON. -/
def jsonEscape (s : String) : String :=
  s.replace "\\" "\\\\" |>.replace "\"" "\\\"" |>.replace "\n" "\\n"

/-- Pretty-print a type expression. Output is informational (safe to include
in `premise/final.json`); not guaranteed to be re-parseable as Lean source. -/
def ppType (env : Environment) (type : Expr) : IO String := do
  let opts := Options.empty
    |>.setBool `pp.universes false
    |>.setBool `pp.fullNames false
    |>.setBool `pp.unicode true
  let ctxCore : Core.Context := {
    fileName := "<verification_extract>"
    fileMap := .ofString ""
    options := opts
  }
  let stCore : Core.State := { env }
  let (result, _) ← (do
    let fmt ← Meta.MetaM.run' (Meta.ppExpr type)
    return fmt.pretty (width := 120)
  : CoreM String).toIO ctxCore stCore
  return result

def headerChallenge : String :=
"-- GENERATED BY scripts/build_verification.sh. DO NOT EDIT.
-- Source: Verification/Headlines.lean

import Verification.Definitions

-- Phase-3 status: hand-written crown-jewel statements pending activation of Tier 3
-- comparator. Until then, each headline is tracked as a named comment. The
-- extractor regenerates this file deterministically so that CI diff-checks pass.

"

def headerSolution : String :=
"-- GENERATED BY scripts/build_verification.sh. DO NOT EDIT.
-- Source: Verification/Headlines.lean

import Verification.Definitions
import ZPM

-- Re-exports of ZPM headlines. Lean's type elaboration copies each original
-- theorem's type onto its `challenge_*` alias automatically, so this file
-- requires no pretty-printer round-trip.

"

/-- Challenge placeholder: one TODO comment per headline. -/
def emitChallenge (hs : List Name) : IO Unit := do
  IO.print headerChallenge
  if hs.isEmpty then
    IO.println "-- No headline theorems declared yet."
  else
    for n in hs do
      IO.println s!"-- TODO(tier-3): challenge statement for {n}"

/-- Solution: simple re-export per headline. -/
def emitSolution (hs : List Name) : IO Unit := do
  IO.print headerSolution
  if hs.isEmpty then
    IO.println "-- No headline theorems declared yet."
  else
    for n in hs do
      IO.println s!"noncomputable def challenge_{flatName n} := @{n}"

/-- Premise JSON: `{ "theorems": [ { "name", "type" } ... ] }` with names fully
qualified and types pretty-printed. -/
def emitPremise (env : Environment) (hs : List Name) : IO Unit := do
  IO.println "{"
  if hs.isEmpty then
    IO.println "  \"theorems\": []"
  else
    IO.println "  \"theorems\": ["
    let total := hs.length
    let mut idx : Nat := 0
    for n in hs do
      let typeStr ← match env.find? n with
        | some (.thmInfo ti) => ppType env ti.type
        | _ => pure "<unknown>"
      let sep := if idx + 1 < total then "," else ""
      IO.println s!"    \{ \"name\": \"{n}\", \"type\": \"{jsonEscape typeStr}\" }{sep}"
      idx := idx + 1
    IO.println "  ]"
  IO.println "}"

end Verification.Extract

open Verification.Extract Verification.Headlines

unsafe def main (args : List String) : IO Unit := do
  let mode := args.head?.getD ""
  match mode with
  | "challenge" => emitChallenge headlines
  | "solution"  => emitSolution headlines
  | "premise"   => do
      initSearchPath (← Lean.findSysroot)
      let mods : Array Import := #[
        { module := `ZPM : Import },
        { module := `Verification.Definitions : Import },
        { module := `Verification.Headlines : Import }
      ]
      let env ← importModules mods {}
      emitPremise env headlines
  | _ => do
      IO.eprintln "usage: verification_extract {challenge|solution|premise}"
      IO.Process.exit 1
