/-
Copyright (c) 2026 Dhruv Gupta. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dhruv Gupta
-/

import Lean
import Verification.Definitions

/-!
# Verification.Extract

Lean executable that auto-discovers every public theorem in `ZPM.*`
modules and regenerates five artifacts:

- `Verification/ChallengeCrown.lean`: one
  `theorem challenge_<flat> : <type> := sorry` per discovered theorem.
- `Verification/SolutionCrown.lean`: the matching
  `theorem challenge_<flat> : <type> := @<fully-qualified-name>` per
  discovered theorem.
- `Verification/config.crown.json`: comparator config listing every
  `challenge_<flat>` name, permitted axioms, nanoda flag.
- `Verification/PrintAxioms.lean`: `#print axioms challenge_<flat>` per
  theorem, fed through `lake env lean` in Tier 1 / Tier 2.
- `premise/final.json`: JSON inventory of `{ name, type }` pairs.

Type signatures are produced by `PrettyPrinter.delab` (round-trip-safe
delaborator) rather than `Meta.ppExpr` (reader-friendly formatter), so
the emitted Lean source re-parses cleanly.

Invoked by `scripts/build_verification.sh` in five modes (`challenge`,
`solution`, `premise`, `config`, `axioms`). CI regenerates and
`git diff --exit-code`s the five files to catch drift.
-/

open Lean Lean.PrettyPrinter

namespace Verification.Extract

/-- A module is one of the `ZPM` submodules (or `ZPM` itself). -/
def isZPMModule : Name → Bool
  | .str .anonymous "ZPM" => true
  | .str p _ => isZPMModule p
  | _ => false

/-- Lean auto-generates lemmas for every `def`/`structure`:
- equation lemmas: `foo.eq_1`, `foo.eq_def`
- congruence simp lemmas: `foo.congr_simp`, `Foo.mk.congr_simp`
- structure injectivity: `Foo.mk.inj`, `Foo.mk.injEq`
- SizeOf spec: `Foo.mk.sizeOf_spec`
- no-confusion: `Foo.noConfusion`, `Foo.noConfusionType`

These are theorems in the kernel sense but not user-declared content. Filter them. -/
def isAutoGenerated : Name → Bool
  | .str _ s =>
    s == "eq_def" ||
    (s.startsWith "eq_" && (s.drop 3).all Char.isDigit) ||
    s == "congr_simp" ||
    s == "congr" ||
    s == "injEq" ||
    s == "sizeOf_spec" ||
    s == "noConfusion" ||
    s == "noConfusionType"
  | _ => false

/-- `n` is a public, user-declared theorem living in a `ZPM.*` module. -/
def isPublicZPMTheorem (env : Environment) (n : Name) : Bool :=
  if n.isInternal then false
  else if isAutoGenerated n then false
  else
    match env.find? n with
    | some (.thmInfo _) =>
      match env.getModuleIdxFor? n with
      | some idx =>
        match env.header.moduleNames[idx.toNat]? with
        | some m => isZPMModule m
        | none => false
      | none => false
    | _ => false

/-- Replace dots with underscores so a fully-qualified name becomes a valid
unqualified Lean identifier. -/
def flatName (n : Name) : String :=
  n.toString.replace "." "_"

/-- Escape a string for JSON. -/
def jsonEscape (s : String) : String :=
  s.replace "\\" "\\\\" |>.replace "\"" "\\\"" |>.replace "\n" "\\n"

/-- Common pretty-printer options for re-parseable output.

- `pp.universes true` + header `universe u u_1 ...` resolves universe variables.
- `pp.funBinderTypes`/`pp.piBinderTypes` force explicit binder types so
  anonymous-binder type inference doesn't choke on shadowed names.
- `pp.proofs true` + `pp.deepTerms true` suppresses the `⋯` ellipsis that
  otherwise replaces deeply-nested instance projections and proof terms
  inside theorem statements (e.g. `tvDistReal P Q hP hQ`, `HasDerivAt`
  normed-field instances). Without these, the emitted source contains
  `⋯` tokens that Lean cannot parse.
- Short names + `import ZPM` handles name resolution. -/
def reparseableOpts : Options :=
  Options.empty
    |>.setBool `pp.universes true
    |>.setBool `pp.fullNames false
    |>.setBool `pp.notation true
    |>.setBool `pp.unicode true
    |>.setBool `pp.funBinderTypes true
    |>.setBool `pp.piBinderTypes true
    |>.setBool `pp.proofs true
    |>.setBool `pp.proofs.withType false
    |>.setBool `pp.deepTerms true
    |>.setBool `pp.explicit true

/-- Informational pretty-printer options for `premise/final.json`. -/
def infoOpts : Options :=
  Options.empty
    |>.setBool `pp.universes false
    |>.setBool `pp.fullNames false
    |>.setBool `pp.unicode true

/-- Pretty-print an expression as re-parseable Lean via delab + ppTerm. -/
def ppTermViaDelab (env : Environment) (e : Expr) : IO String := do
  let ctxCore : Core.Context := {
    fileName := "<verification_extract>"
    fileMap := .ofString ""
    options := reparseableOpts
  }
  let stCore : Core.State := { env }
  let (result, _) ← (do
    let fmt ← Meta.MetaM.run' (do
      let stx ← delab e
      PrettyPrinter.ppTerm stx)
    return fmt.pretty (width := 120)
  : CoreM String).toIO ctxCore stCore
  return result

/-- Informational pretty-print (reader-friendly, not round-trip-safe). -/
def ppTypeInfo (env : Environment) (e : Expr) : IO String := do
  let ctxCore : Core.Context := {
    fileName := "<verification_extract>"
    fileMap := .ofString ""
    options := infoOpts
  }
  let stCore : Core.State := { env }
  let (result, _) ← (do
    let fmt ← Meta.MetaM.run' (Meta.ppExpr e)
    return fmt.pretty (width := 120)
  : CoreM String).toIO ctxCore stCore
  return result

/-- Collect all public ZPM theorems, sorted for deterministic output. -/
def collectHeadlines (env : Environment) : Array Name := Id.run do
  let mut acc : Array Name := #[]
  for (n, _info) in env.constants.toList do
    if isPublicZPMTheorem env n then
      acc := acc.push n
  acc.qsort (fun a b => a.toString < b.toString)

def headerChallenge : String :=
"-- GENERATED BY scripts/build_verification.sh. DO NOT EDIT.
-- Source: auto-discovered public theorems in ZPM.*

import Verification.Definitions
import ZPM

set_option linter.unusedVariables false

universe u u_1 u_2 u_3 u_4 u_5 u_6 u_7 u_8 u_9 u_10

"

def headerSolution : String :=
"-- GENERATED BY scripts/build_verification.sh. DO NOT EDIT.
-- Source: auto-discovered public theorems in ZPM.*

import Verification.Definitions
import ZPM

set_option linter.unusedVariables false

universe u u_1 u_2 u_3 u_4 u_5 u_6 u_7 u_8 u_9 u_10

"

def emitChallenge (env : Environment) (hs : Array Name) : IO Unit := do
  IO.print headerChallenge
  if hs.isEmpty then
    IO.println "-- No public ZPM theorems discovered."
  else
    for n in hs do
      match env.find? n with
      | some (.thmInfo ti) =>
        let typeStr ← ppTermViaDelab env ti.type
        IO.println s!"theorem challenge_{flatName n} : {typeStr} := sorry"
      | _ => IO.eprintln s!"warning: {n} not a theorem"

def emitSolution (env : Environment) (hs : Array Name) : IO Unit := do
  IO.print headerSolution
  if hs.isEmpty then
    IO.println "-- No public ZPM theorems discovered."
  else
    for n in hs do
      match env.find? n with
      | some (.thmInfo ti) =>
        let typeStr ← ppTermViaDelab env ti.type
        IO.println s!"theorem challenge_{flatName n} : {typeStr} := @{n}"
      | _ => IO.eprintln s!"warning: {n} not a theorem"

def headerPrintAxioms : String :=
"-- GENERATED BY scripts/build_verification.sh. DO NOT EDIT.
-- Source: auto-discovered public theorems in ZPM.*

import Verification.SolutionCrown

"

def emitPrintAxioms (hs : Array Name) : IO Unit := do
  IO.print headerPrintAxioms
  if hs.isEmpty then
    IO.println "-- No public ZPM theorems discovered."
  else
    for n in hs do
      IO.println s!"#print axioms challenge_{flatName n}"

def emitConfig (hs : Array Name) : IO Unit := do
  IO.println "{"
  IO.println "  \"challenge_module\": \"Verification.ChallengeCrown\","
  IO.println "  \"solution_module\": \"Verification.SolutionCrown\","
  if hs.isEmpty then
    IO.println "  \"theorem_names\": [],"
  else
    IO.println "  \"theorem_names\": ["
    let total := hs.size
    let mut idx : Nat := 0
    for n in hs do
      let sep := if idx + 1 < total then "," else ""
      IO.println s!"    \"challenge_{flatName n}\"{sep}"
      idx := idx + 1
    IO.println "  ],"
  IO.println "  \"permitted_axioms\": [\"propext\", \"Quot.sound\", \"Classical.choice\"],"
  IO.println "  \"enable_nanoda\": false"
  IO.println "}"

def emitPremise (env : Environment) (hs : Array Name) : IO Unit := do
  IO.println "{"
  if hs.isEmpty then
    IO.println "  \"theorems\": []"
  else
    IO.println "  \"theorems\": ["
    let total := hs.size
    let mut idx : Nat := 0
    for n in hs do
      let typeStr ← match env.find? n with
        | some (.thmInfo ti) => ppTypeInfo env ti.type
        | _ => pure "<unknown>"
      let sep := if idx + 1 < total then "," else ""
      IO.println s!"    \{ \"name\": \"{n}\", \"type\": \"{jsonEscape typeStr}\" }{sep}"
      idx := idx + 1
    IO.println "  ]"
  IO.println "}"

end Verification.Extract

open Verification.Extract

unsafe def main (args : List String) : IO Unit := do
  initSearchPath (← Lean.findSysroot)
  let mods : Array Import := #[
    { module := `ZPM : Import },
    { module := `Verification.Definitions : Import }
  ]
  let env ← importModules mods {}
  let headlines := collectHeadlines env
  let mode := args.head?.getD ""
  match mode with
  | "challenge" => emitChallenge env headlines
  | "solution"  => emitSolution env headlines
  | "premise"   => emitPremise env headlines
  | "config"    => emitConfig headlines
  | "axioms"    => emitPrintAxioms headlines
  | _ => do
      IO.eprintln "usage: verification_extract {challenge|solution|premise|config|axioms}"
      IO.Process.exit 1
