-- GENERATED BY scripts/build_verification.sh. DO NOT EDIT.
-- Source: Verification/Headlines.lean

import Verification.Definitions
import ZPM

-- TODO(phase-1): solution for MeasureTheory.AnalyticSet.nullMeasurableSet
-- TODO(phase-1): solution for MeasureTheory.AnalyticSet.compactCap_eq
-- TODO(phase-1): solution for MeasureTheory.AnalyticSet.cap_eq_iSup_isCompact
-- TODO(phase-1): solution for ProbabilityTheory.chebyshev_majority_bound
-- TODO(phase-1): solution for BinaryMatrix.assouad_transpose_vcDim
-- TODO(phase-1): solution for ProbabilityTheory.covering_minimax
-- TODO(phase-1): solution for ProbabilityTheory.finite_approx_minimax
-- TODO(phase-1): solution for ProbabilityTheory.mwu_potential_T_bound
-- TODO(phase-1): solution for ProbabilityTheory.mwu_approx_minimax
